[package]
name = "keystore-cracker"
version = "0.1.0"
edition = "2021"

[dependencies]
eth-keystore = "0.1"
serde_json = "1.0"
hex = "0.4"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
rayon = "1.7"

# [profile.release]
# opt-level = 2
# debug = true

